Pit modal 2
infoshareacademy/jfdzw1-ipmdotdev pull request #24
Opened 2017-12-13 20:02 UTC by piotryfon

Sprawdziłem wszystko, dalej nie podmienia imienia. Załamka.

2017-12-14 19:05 UTC, piotryfon commented
Modal działa, adres wywołania podmienia się (przyjmuje parametr - nazwę usera).

2017-12-15 08:08 UTC, 84lukaszkaminski requested changes
popraw kod względem moich komentarzy i doklej brancha do developa.
ps. pokasuj stare, niepotrzebne branche i pull requesty

2017-12-15 08:08 UTC, 84lukaszkaminski commented on game/index.html
> +    <div class="modal fade" id="gameModal" role="dialog">
znowu problem z nazwą. ten modal renderuje ranking, a nie grę

2017-12-15 08:08 UTC, 84lukaszkaminski commented on index.html
> +                    //$("#game-container").attr('data', './game?name=' + userName);
to powinno zadziałać, jak strona będzie wgrana na serwer. ale niech będzie z index.html - dobrze, ze do tego sam doszedłeś. skasuj zakomentowany kod.

2017-12-16 11:19 UTC, merged